backend:
  name: git-gateway
  branch: main # Branch to update (optional; defaults to master)

media_folder: static/uploads
public_folder: uploads

collections:
  - name: 'blog'
    label: 'Blog'
    folder: 'content/blog'
    create: true
    slug: 'index'
    path: '{{title}}/index'
    editor:
      preview: true
    fields:
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Author', name: 'author', widget: 'string' }
      - { label: 'Featured Image', name: 'img', widget: 'image' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Description', name: 'description', widget: 'string' }
      - { label: 'Body', name: 'body', widget: 'markdown' }
      - label: "Related posts"
        name: "relatedPosts"
        widget: "relation"
        collection: "blog"
        search_fields: ["title", "author"]
        display_fields: ["title"]
        value_field: "title"